
const projectList = [
  // {"_id":1,"name":"Monster Money","description":"An app to teach teenagers financial literacy through the care of a monster","github":"https://github.com/Paper-Trail-Project","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/Screen+Shot+2020-07-10+at+1.45.04+PM.png", "component": "walldrawing", "image_url": "none"},

  {"_id":1,"name":"D3 Bar Chart","description":"A simple bar chart using D3.js to show my daily FitBit steps. Check out the video for a rundown of how to build one yourself!","github":"https://github.com/merestrickland/D3-BarChart","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/D3+Barchart.mp4", "component": "mediademo", "image_url": "none"},

  {"_id":2,"name":"Blobbers","description":"An interactive JavaScript SPA where the user gains points by grabbing pieces of the sun, or loses points by running into the falling rain. Game was built with JavaScript and P5.js","demoVid":"https://www.youtube.com/watch?v=CHfE7pHK0gU","toolsUsed":"JavaScript, P5.js","github":"https://github.com/jralorro93/blobbers-frontend","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/Blobbers.mp4","component": "mediademo"},

  {"_id":3,"name":"Trip List","description":"A website where users can add recommendations of things to do on upcoming or previous trips. I built this because I wanted an easier way to send recommendations to friends. Built with a React front end and a Ruby on Rails back end.","demoVid":"https://www.youtube.com/watch?v=D8qmIOkQbvY","toolsUsed":"JavaScript, React, Redux, Ruby on Rails","github":"https://github.com/merestrickland/TripList-frontend","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/TripList+Demo.mp4", "component": "mediademo", "image_url": "https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/triplist.png"},

  {"_id":4,"name":"Rita","description":"Prototype for an app that helps caregivers communicate with each other and keep track of appointments and medications. Prototype was built in InVision. ***Winner of the \"People's Choice Award\" at LYLAS Labs: Women at Work Hackathon***","demoVid":"https://www.youtube.com/watch?v=SylcQAxbskc","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/Rita+Demo1.mp4", "component": "mediademo"},

  {"_id":5,"name":"Wall Drawing","description":"Sol Lewitt was a conceptual artist, and is well-known for his wall drawings which can be created by anyone following the instructions he has outlined. This leaves a lot of room for interpretation by the person creating the drawing. Here, I used P5.js to execute his Wall Drawing #17, in which the only instructions are \"Four-part drawing with a different line direction in each part\".","toolsUsed":"JavaScript, HTML, P5.js","github":"https://github.com/merestrickland/P5-Hello/blob/master/src/index.js","image":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/sol.png", "component": "walldrawing"},

  {"_id":6,"name":"Tr(aid)","description":"A web app that empowers members of your community to offer support for those in need, or to ask for resources from others. Built with React front end and Ruby on Rails back end. ***Winner of the Essteem Equalithon***.","demoVid":"https://tr-aid.web.app/","toolsUsed":"JavaScript, React, AWS Firebase, Heroku","github":"https://github.com/equalithon-team-three","media":"https://www.youtube.com/watch?v=_QVQUhjbVqs&feature=emb_logo", "component": "mediademo"},

  {"_id":7,"name":"Gro Cart","description":"A CLI application using Ruby to create shopping lists. A simple app built with pure Ruby","demoVid":"https://www.youtube.com/watch?v=SylcQAxbskc","media":"https://meredith-strickland-portfolio.s3.amazonaws.com/Portfolio/grocart-demo-480.mov", "component": "mediademo"},
]

export default projectList